### ISSUE TITLE
Replaced here a deprecated function

### ISSUE THREAD

**Issue by miguelpragier** [alvarotrigo/PHP-Backend#1]
Hello!

I've replaced the deprecated function ereg_replace, within function setFormat() like this:
153:    private function setFormat(){
154:		$pathInfo = pathinfo($this->imagePath);
155:		$extension = $pathInfo['extension'];
156:		$this->format = strtoupper($extension);

And now it's even compatible with php7

Thank you very much for your work and sharing!

**Comment by alvarotrigo** [comment]
Thanks!! Feel free to provide a pull request!

**Comment by alvarotrigo** [comment]
Solved! Thanks!
